version: 2

models:
  - name: int_weather_hourly_lookup
    description: "Hourly-level weather records derived from timestamp."
    columns:
      - name: airport_code
      - name: weather_hour
      - name: temperature_c
      - name: weather_desc
      - name: weather_severity
      - name: wind_speed_mps
      - name: visibility_m

  - name: int_flights_weather_joined
    description: "Combines flight, weather, and cause delay data for further KPI analysis."
    columns:
      - name: FlightDate
      - name: Origin
      - name: ScheduledDepartureTime
      - name: DepDelayMinutes
      - name: WEATHER_DELAY
      - name: CARRIER_DELAY
      - name: weather_condition
      - name: weather_severity
