name: flight_weather_project
version: '1.0'

profile: default  

model-paths: ["models"]

analysis-paths: ["analysis"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  flight_weather_project:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: view
