version: 2

sources:
  - name: flight_delay_analytics
    database: dbt-flight-and-weather
    schema: flight_delay_analytics
    tables:
      - name: raw_flight_delays
      - name: raw_cause_delays
      - name: raw_weather_logs

models:
  - name: stg_flight_delays
    description: "Cleans and engineers raw flight delay data for downstream analysis."
    columns:
      - name: FlightDate
        description: "Date of the flight."
      - name: Airline
        description: "Airline carrier code."
      - name: Origin
        description: "Origin airport code."
      - name: Dest
        description: "Destination airport code."
      - name: ScheduledDepartureTime
        description: "Scheduled departure timestamp (datetime)."
      - name: scheduled_hour
        description: "Extracted hour of the day from CRSDepTime."
      - name: DepDelayMinutes
        description: "Departure delay in minutes."
      - name: is_delayed
        description: "Binary flag if delay >= 15 minutes."
      - name: delay_bucket
        description: "Bucketed delay range: On Time, 15–30 min, 30–60 min, >60 min."
      - name: is_peak_hour
        description: "True if scheduled between 7–10 AM or 5–8 PM."

  - name: stg_cause_delays
    description: "Extracts and renames fields from raw cause-specific delay data."
    columns:
      - name: FlightDate
        description: "Date of the flight."
      - name: Origin
        description: "Origin airport code."
      - name: Dest
        description: "Destination airport code."
      - name: CARRIER_DELAY
      - name: WEATHER_DELAY
      - name: NAS_DELAY
      - name: SECURITY_DELAY
      - name: LATE_AIRCRAFT_DELAY
      - name: CANCELLATION_CODE

  - name: stg_weather_logs
    description: "Standardizes and categorizes real-time weather logs for joins."
    columns:
      - name: airport_code
      - name: timestamp_utc
      - name: weather_hour
      - name: temperature_c
      - name: wind_speed_mps
      - name: visibility_m
      - name: weather_desc
      - name: weather_condition
      - name: weather_severity
