version: 2

models:
  - name: marts_weather_delay_impact
    description: "Aggregated flight delays by weather and severity level."
    columns:
      - name: Origin
      - name: weather_condition
      - name: scheduled_hour
      - name: total_flights
      - name: avg_dep_delay
      - name: delay_rate
      - name: long_delay_pct
      - name: cancel_rate

  - name: marts_time_delay_trends
    description: "Rolling average delay per airport to monitor trends."
    columns:
      - name: FlightDate
      - name: Airline
      - name: Origin
      - name: scheduled_hour
      - name: rolling_7_day_avg_delay
      - name: flights_last_7_days

  - name: marts_delay_risk_scoring_model
    description: "Risk scoring logic combining avg delay and weather severity."
    columns:
      - name: Origin
      - name: Airline
      - name: weather_condition
      - name: scheduled_hour
      - name: avg_dep_delay
      - name: weather_severity
      - name: delay_risk_score
