version: 2

models:
  - name: dim_airports
    description: "Unique list of airports from Origin/Dest fields."
    columns:
      - name: dim_airports
        description: "Airport dimension with state and city info"
        columns:
          - name: airport_code
            tests:
              - not_null
              - unique
          - name: city
          - name: state_name
        

  - name: dim_airlines
    description: "List of airline carriers."
    columns:
      - name: airline_name
        description: "Airline name as found in flight records."

  - name: dim_time
    description: "Calendar and time metadata from flight dates."
    columns:
      - name: FlightDate
      - name: day_of_week
      - name: month
      - name: year
      - name: is_weekend

